Run project tests as part of template testing
SAFE-Stack/SAFE-template pull request #623
Opened 2024-07-12 14:15 UTC by Larocceau

* Add build action in default project to run tests one-off using mocha test runner (instead of in browser)
* Add build action in template build script to run these tests

2024-07-12 14:57 UTC, mattgallagher92 requested changes
This looks like a good step in the right direction 🙂 I've made a few suggestions

2024-07-12 14:57 UTC, mattgallagher92 commented on azure-pipelines.yml
What's the reason for changing to double quotes?

2024-07-12 14:57 UTC, mattgallagher92 commented on Content/default/Helpers.fs
> +let npm: seq<string> -> string -> CreateProcess<ProcessResult<unit>> =
```suggestion
let npm : seq<string> -> string -> CreateProcess<ProcessResult<unit>> = 
```

Formatting nitpick. Perhaps worth running fantomas?

2024-07-12 14:57 UTC, mattgallagher92 commented on Content/default/Helpers.fs
Why bother with the type annotations?

2024-07-12 14:57 UTC, mattgallagher92 commented on Content/default/Build.fs
> +    "restoreClientDependencies" ==> "Tests"
```suggestion
    "RestoreClientDependencies" ==> "Tests"
```

2024-07-12 14:57 UTC, mattgallagher92 commented on Build.fs
I'm not sure that the terminology is quite precise enough here. I'd go for "default _template_ tests" and "template _execution_ tests".

2024-07-12 14:57 UTC, mattgallagher92 commented on Content/default/Build.fs
Maybe to make the distinction clearer, we should call these targets "RunTestsHeadless" and "WatchRunTests"?

If we rename "RunTests" we should also update docs, so I'm happy for that to be split into a separate issue/PR rather than done now.

2024-07-12 15:07 UTC, Larocceau commented on Content/default/Helpers.fs
Yeah I get this weird error about these functions being generic? I don't understand how, but the annotations fix it

2024-07-12 15:11 UTC, Larocceau commented on azure-pipelines.yml
OH YIKES, my ide did that. Will revert

2024-07-12 15:24 UTC, Larocceau commented on Content/default/Build.fs
did the rename for runTestsHeadless, let's do the other change next week in conjunction with a docs update

2024-07-16 08:42 UTC, Larocceau commented
All feedback dealt with

2024-07-16 09:14 UTC, mattgallagher92 commented on Content/default/Build.fs
Thanks! Could you raise an issue to make sure that we remember to do that?

2024-07-16 09:16 UTC, mattgallagher92 commented on Content/default/Helpers.fs
Let's discuss.

2024-07-19 13:23 UTC, mattgallagher92 commented on Content/default/Build.fs
Let's make sure to update the docs too 👍🏼

2024-07-19 13:23 UTC, mattgallagher92 approved these changes
Happy for this to be merged so long as the docs are updated to reflect the changed target name

2024-07-19 14:00 UTC, mattgallagher92 requested changes
Oh, one last thing: the template's README needs updating to reflect the changed target name.

2024-07-19 16:42 UTC, mattgallagher92 approved these changes

2024-07-26 11:35 UTC, mattgallagher92 commented
My last comment is wrong - the README had already been updated.

2024-07-26 11:35 UTC, merged